//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Application.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTitleField, value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIDField;
        
        private System.Nullable<int> EmployeeIDField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Products : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Demo_Application.ServiceReference1.HelloWorldResponse HelloWorld(Demo_Application.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Demo_Application.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Demo_Application.ServiceReference1.AddResponse Add(Demo_Application.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddResponse> AddAsync(Demo_Application.ServiceReference1.AddRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        Demo_Application.ServiceReference1.EditResponse Edit(Demo_Application.ServiceReference1.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.EditResponse> EditAsync(Demo_Application.ServiceReference1.EditRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        Demo_Application.ServiceReference1.DeleteResponse Delete(Demo_Application.ServiceReference1.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.DeleteResponse> DeleteAsync(Demo_Application.ServiceReference1.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerData", ReplyAction="*")]
        Demo_Application.ServiceReference1.CustomerDataResponse CustomerData(Demo_Application.ServiceReference1.CustomerDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerData", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.CustomerDataResponse> CustomerDataAsync(Demo_Application.ServiceReference1.CustomerDataRequest request);
        
        // CODEGEN: Generating message contract since element name Customer1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdersData", ReplyAction="*")]
        Demo_Application.ServiceReference1.OrdersDataResponse OrdersData(Demo_Application.ServiceReference1.OrdersDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdersData", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.OrdersDataResponse> OrdersDataAsync(Demo_Application.ServiceReference1.OrdersDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        Demo_Application.ServiceReference1.PlaceOrderResponse PlaceOrder(Demo_Application.ServiceReference1.PlaceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.PlaceOrderResponse> PlaceOrderAsync(Demo_Application.ServiceReference1.PlaceOrderRequest request);
        
        // CODEGEN: Generating message contract since element name AddProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        Demo_Application.ServiceReference1.AddProductsResponse AddProducts(Demo_Application.ServiceReference1.AddProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddProductsResponse> AddProductsAsync(Demo_Application.ServiceReference1.AddProductsRequest request);
        
        // CODEGEN: Generating message contract since element name AddEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployees", ReplyAction="*")]
        Demo_Application.ServiceReference1.AddEmployeesResponse AddEmployees(Demo_Application.ServiceReference1.AddEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddEmployeesResponse> AddEmployeesAsync(Demo_Application.ServiceReference1.AddEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Demo_Application.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Demo_Application.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Demo_Application.ServiceReference1.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string ID, string CompName, string CustName, string CustTitle, string Address) {
            this.ID = ID;
            this.CompName = CompName;
            this.CustName = CustName;
            this.CustTitle = CustTitle;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Demo_Application.ServiceReference1.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(bool AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.EditRequestBody Body;
        
        public EditRequest() {
        }
        
        public EditRequest(Demo_Application.ServiceReference1.EditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public EditRequestBody() {
        }
        
        public EditRequestBody(string ID, string CompName, string CustName, string CustTitle, string Address) {
            this.ID = ID;
            this.CompName = CompName;
            this.CustName = CustName;
            this.CustTitle = CustTitle;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.EditResponseBody Body;
        
        public EditResponse() {
        }
        
        public EditResponse(Demo_Application.ServiceReference1.EditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditResult;
        
        public EditResponseBody() {
        }
        
        public EditResponseBody(bool EditResult) {
            this.EditResult = EditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(Demo_Application.ServiceReference1.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(Demo_Application.ServiceReference1.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(bool DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerData", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.CustomerDataRequestBody Body;
        
        public CustomerDataRequest() {
        }
        
        public CustomerDataRequest(Demo_Application.ServiceReference1.CustomerDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CustomerDataRequestBody {
        
        public CustomerDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.CustomerDataResponseBody Body;
        
        public CustomerDataResponse() {
        }
        
        public CustomerDataResponse(Demo_Application.ServiceReference1.CustomerDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo_Application.ServiceReference1.Customer[] CustomerDataResult;
        
        public CustomerDataResponseBody() {
        }
        
        public CustomerDataResponseBody(Demo_Application.ServiceReference1.Customer[] CustomerDataResult) {
            this.CustomerDataResult = CustomerDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersData", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.OrdersDataRequestBody Body;
        
        public OrdersDataRequest() {
        }
        
        public OrdersDataRequest(Demo_Application.ServiceReference1.OrdersDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdersDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo_Application.ServiceReference1.Customer[] Customer1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int i;
        
        public OrdersDataRequestBody() {
        }
        
        public OrdersDataRequestBody(Demo_Application.ServiceReference1.Customer[] Customer1, int i) {
            this.Customer1 = Customer1;
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.OrdersDataResponseBody Body;
        
        public OrdersDataResponse() {
        }
        
        public OrdersDataResponse(Demo_Application.ServiceReference1.OrdersDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdersDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo_Application.ServiceReference1.OrderDetails[] OrdersDataResult;
        
        public OrdersDataResponseBody() {
        }
        
        public OrdersDataResponseBody(Demo_Application.ServiceReference1.OrderDetails[] OrdersDataResult) {
            this.OrdersDataResult = OrdersDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrder", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.PlaceOrderRequestBody Body;
        
        public PlaceOrderRequest() {
        }
        
        public PlaceOrderRequest(Demo_Application.ServiceReference1.PlaceOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int EmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Quantity;
        
        public PlaceOrderRequestBody() {
        }
        
        public PlaceOrderRequestBody(string CustomerID, int EmployeeID, string ProductName, int Quantity) {
            this.CustomerID = CustomerID;
            this.EmployeeID = EmployeeID;
            this.ProductName = ProductName;
            this.Quantity = Quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.PlaceOrderResponseBody Body;
        
        public PlaceOrderResponse() {
        }
        
        public PlaceOrderResponse(Demo_Application.ServiceReference1.PlaceOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PlaceOrderResult;
        
        public PlaceOrderResponseBody() {
        }
        
        public PlaceOrderResponseBody(bool PlaceOrderResult) {
            this.PlaceOrderResult = PlaceOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProducts", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.AddProductsRequestBody Body;
        
        public AddProductsRequest() {
        }
        
        public AddProductsRequest(Demo_Application.ServiceReference1.AddProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProductsRequestBody {
        
        public AddProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.AddProductsResponseBody Body;
        
        public AddProductsResponse() {
        }
        
        public AddProductsResponse(Demo_Application.ServiceReference1.AddProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo_Application.ServiceReference1.Products[] AddProductsResult;
        
        public AddProductsResponseBody() {
        }
        
        public AddProductsResponseBody(Demo_Application.ServiceReference1.Products[] AddProductsResult) {
            this.AddProductsResult = AddProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployees", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.AddEmployeesRequestBody Body;
        
        public AddEmployeesRequest() {
        }
        
        public AddEmployeesRequest(Demo_Application.ServiceReference1.AddEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddEmployeesRequestBody {
        
        public AddEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo_Application.ServiceReference1.AddEmployeesResponseBody Body;
        
        public AddEmployeesResponse() {
        }
        
        public AddEmployeesResponse(Demo_Application.ServiceReference1.AddEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo_Application.ServiceReference1.Employees[] AddEmployeesResult;
        
        public AddEmployeesResponseBody() {
        }
        
        public AddEmployeesResponseBody(Demo_Application.ServiceReference1.Employees[] AddEmployeesResult) {
            this.AddEmployeesResult = AddEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Demo_Application.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Demo_Application.ServiceReference1.WebService1Soap>, Demo_Application.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.HelloWorldResponse Demo_Application.ServiceReference1.WebService1Soap.HelloWorld(Demo_Application.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Demo_Application.ServiceReference1.HelloWorldRequest inValue = new Demo_Application.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Demo_Application.ServiceReference1.HelloWorldRequestBody();
            Demo_Application.ServiceReference1.HelloWorldResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.HelloWorldResponse> Demo_Application.ServiceReference1.WebService1Soap.HelloWorldAsync(Demo_Application.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Demo_Application.ServiceReference1.HelloWorldRequest inValue = new Demo_Application.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Demo_Application.ServiceReference1.HelloWorldRequestBody();
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.AddResponse Demo_Application.ServiceReference1.WebService1Soap.Add(Demo_Application.ServiceReference1.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public bool Add(string ID, string CompName, string CustName, string CustTitle, string Address) {
            Demo_Application.ServiceReference1.AddRequest inValue = new Demo_Application.ServiceReference1.AddRequest();
            inValue.Body = new Demo_Application.ServiceReference1.AddRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            Demo_Application.ServiceReference1.AddResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddResponse> Demo_Application.ServiceReference1.WebService1Soap.AddAsync(Demo_Application.ServiceReference1.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddResponse> AddAsync(string ID, string CompName, string CustName, string CustTitle, string Address) {
            Demo_Application.ServiceReference1.AddRequest inValue = new Demo_Application.ServiceReference1.AddRequest();
            inValue.Body = new Demo_Application.ServiceReference1.AddRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.EditResponse Demo_Application.ServiceReference1.WebService1Soap.Edit(Demo_Application.ServiceReference1.EditRequest request) {
            return base.Channel.Edit(request);
        }
        
        public bool Edit(string ID, string CompName, string CustName, string CustTitle, string Address) {
            Demo_Application.ServiceReference1.EditRequest inValue = new Demo_Application.ServiceReference1.EditRequest();
            inValue.Body = new Demo_Application.ServiceReference1.EditRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            Demo_Application.ServiceReference1.EditResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).Edit(inValue);
            return retVal.Body.EditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.EditResponse> Demo_Application.ServiceReference1.WebService1Soap.EditAsync(Demo_Application.ServiceReference1.EditRequest request) {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.EditResponse> EditAsync(string ID, string CompName, string CustName, string CustTitle, string Address) {
            Demo_Application.ServiceReference1.EditRequest inValue = new Demo_Application.ServiceReference1.EditRequest();
            inValue.Body = new Demo_Application.ServiceReference1.EditRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.DeleteResponse Demo_Application.ServiceReference1.WebService1Soap.Delete(Demo_Application.ServiceReference1.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string ID) {
            Demo_Application.ServiceReference1.DeleteRequest inValue = new Demo_Application.ServiceReference1.DeleteRequest();
            inValue.Body = new Demo_Application.ServiceReference1.DeleteRequestBody();
            inValue.Body.ID = ID;
            Demo_Application.ServiceReference1.DeleteResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.DeleteResponse> Demo_Application.ServiceReference1.WebService1Soap.DeleteAsync(Demo_Application.ServiceReference1.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.DeleteResponse> DeleteAsync(string ID) {
            Demo_Application.ServiceReference1.DeleteRequest inValue = new Demo_Application.ServiceReference1.DeleteRequest();
            inValue.Body = new Demo_Application.ServiceReference1.DeleteRequestBody();
            inValue.Body.ID = ID;
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.CustomerDataResponse Demo_Application.ServiceReference1.WebService1Soap.CustomerData(Demo_Application.ServiceReference1.CustomerDataRequest request) {
            return base.Channel.CustomerData(request);
        }
        
        public Demo_Application.ServiceReference1.Customer[] CustomerData() {
            Demo_Application.ServiceReference1.CustomerDataRequest inValue = new Demo_Application.ServiceReference1.CustomerDataRequest();
            inValue.Body = new Demo_Application.ServiceReference1.CustomerDataRequestBody();
            Demo_Application.ServiceReference1.CustomerDataResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).CustomerData(inValue);
            return retVal.Body.CustomerDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.CustomerDataResponse> Demo_Application.ServiceReference1.WebService1Soap.CustomerDataAsync(Demo_Application.ServiceReference1.CustomerDataRequest request) {
            return base.Channel.CustomerDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.CustomerDataResponse> CustomerDataAsync() {
            Demo_Application.ServiceReference1.CustomerDataRequest inValue = new Demo_Application.ServiceReference1.CustomerDataRequest();
            inValue.Body = new Demo_Application.ServiceReference1.CustomerDataRequestBody();
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).CustomerDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.OrdersDataResponse Demo_Application.ServiceReference1.WebService1Soap.OrdersData(Demo_Application.ServiceReference1.OrdersDataRequest request) {
            return base.Channel.OrdersData(request);
        }
        
        public Demo_Application.ServiceReference1.OrderDetails[] OrdersData(Demo_Application.ServiceReference1.Customer[] Customer1, int i) {
            Demo_Application.ServiceReference1.OrdersDataRequest inValue = new Demo_Application.ServiceReference1.OrdersDataRequest();
            inValue.Body = new Demo_Application.ServiceReference1.OrdersDataRequestBody();
            inValue.Body.Customer1 = Customer1;
            inValue.Body.i = i;
            Demo_Application.ServiceReference1.OrdersDataResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).OrdersData(inValue);
            return retVal.Body.OrdersDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.OrdersDataResponse> Demo_Application.ServiceReference1.WebService1Soap.OrdersDataAsync(Demo_Application.ServiceReference1.OrdersDataRequest request) {
            return base.Channel.OrdersDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.OrdersDataResponse> OrdersDataAsync(Demo_Application.ServiceReference1.Customer[] Customer1, int i) {
            Demo_Application.ServiceReference1.OrdersDataRequest inValue = new Demo_Application.ServiceReference1.OrdersDataRequest();
            inValue.Body = new Demo_Application.ServiceReference1.OrdersDataRequestBody();
            inValue.Body.Customer1 = Customer1;
            inValue.Body.i = i;
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).OrdersDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.PlaceOrderResponse Demo_Application.ServiceReference1.WebService1Soap.PlaceOrder(Demo_Application.ServiceReference1.PlaceOrderRequest request) {
            return base.Channel.PlaceOrder(request);
        }
        
        public bool PlaceOrder(string CustomerID, int EmployeeID, string ProductName, int Quantity) {
            Demo_Application.ServiceReference1.PlaceOrderRequest inValue = new Demo_Application.ServiceReference1.PlaceOrderRequest();
            inValue.Body = new Demo_Application.ServiceReference1.PlaceOrderRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EmployeeID = EmployeeID;
            inValue.Body.ProductName = ProductName;
            inValue.Body.Quantity = Quantity;
            Demo_Application.ServiceReference1.PlaceOrderResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).PlaceOrder(inValue);
            return retVal.Body.PlaceOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.PlaceOrderResponse> Demo_Application.ServiceReference1.WebService1Soap.PlaceOrderAsync(Demo_Application.ServiceReference1.PlaceOrderRequest request) {
            return base.Channel.PlaceOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.PlaceOrderResponse> PlaceOrderAsync(string CustomerID, int EmployeeID, string ProductName, int Quantity) {
            Demo_Application.ServiceReference1.PlaceOrderRequest inValue = new Demo_Application.ServiceReference1.PlaceOrderRequest();
            inValue.Body = new Demo_Application.ServiceReference1.PlaceOrderRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EmployeeID = EmployeeID;
            inValue.Body.ProductName = ProductName;
            inValue.Body.Quantity = Quantity;
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).PlaceOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.AddProductsResponse Demo_Application.ServiceReference1.WebService1Soap.AddProducts(Demo_Application.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProducts(request);
        }
        
        public Demo_Application.ServiceReference1.Products[] AddProducts() {
            Demo_Application.ServiceReference1.AddProductsRequest inValue = new Demo_Application.ServiceReference1.AddProductsRequest();
            inValue.Body = new Demo_Application.ServiceReference1.AddProductsRequestBody();
            Demo_Application.ServiceReference1.AddProductsResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).AddProducts(inValue);
            return retVal.Body.AddProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddProductsResponse> Demo_Application.ServiceReference1.WebService1Soap.AddProductsAsync(Demo_Application.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddProductsResponse> AddProductsAsync() {
            Demo_Application.ServiceReference1.AddProductsRequest inValue = new Demo_Application.ServiceReference1.AddProductsRequest();
            inValue.Body = new Demo_Application.ServiceReference1.AddProductsRequestBody();
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).AddProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_Application.ServiceReference1.AddEmployeesResponse Demo_Application.ServiceReference1.WebService1Soap.AddEmployees(Demo_Application.ServiceReference1.AddEmployeesRequest request) {
            return base.Channel.AddEmployees(request);
        }
        
        public Demo_Application.ServiceReference1.Employees[] AddEmployees() {
            Demo_Application.ServiceReference1.AddEmployeesRequest inValue = new Demo_Application.ServiceReference1.AddEmployeesRequest();
            inValue.Body = new Demo_Application.ServiceReference1.AddEmployeesRequestBody();
            Demo_Application.ServiceReference1.AddEmployeesResponse retVal = ((Demo_Application.ServiceReference1.WebService1Soap)(this)).AddEmployees(inValue);
            return retVal.Body.AddEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddEmployeesResponse> Demo_Application.ServiceReference1.WebService1Soap.AddEmployeesAsync(Demo_Application.ServiceReference1.AddEmployeesRequest request) {
            return base.Channel.AddEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo_Application.ServiceReference1.AddEmployeesResponse> AddEmployeesAsync() {
            Demo_Application.ServiceReference1.AddEmployeesRequest inValue = new Demo_Application.ServiceReference1.AddEmployeesRequest();
            inValue.Body = new Demo_Application.ServiceReference1.AddEmployeesRequestBody();
            return ((Demo_Application.ServiceReference1.WebService1Soap)(this)).AddEmployeesAsync(inValue);
        }
    }
}
